---
java:
  image: '${IMAGE_NAME}'
  ingressHost: ${SERVICE_FQDN}
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    SERVICES__NOTIFICATIONAPIRESOURCEID: http://vh-notification-api.dev.platform.hmcts.net
    NotifyConfiguration__Environment: Dev

