parameters:
- name: deploymentBranch
  displayName: Branch to Deploy
  type: string
  default: refs/heads/master

- name: environment
  displayName: Environment
  type: string
  default: Sandbox
  values:
  - Preview
  - Dev
  - AAT
  - Sandbox
  - Test1
  - Test2
  - Demo
  - Preprod
  - Prod

- name: RunZap
  displayName: Execute ZAP Tests
  type: boolean
  default: false

- name: prodEnvs
  displayName: Environments Using Prod Subscription
  type: object
  default:
    - Prod
    - Preprod

# Set variables once
variables:
  - group: vh-domains-and-urls
  - group: vh-apps-settings-generic
  - group: vh-notification-api
  - ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
    - ${{ if containsValue(parameters.prodEnvs, parameters.environment) }}:
      - group: vh-prod
    - ${{ if not(containsValue(parameters.prodEnvs, parameters.environment)) }}:
      - group: vh-preview
  - ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
    - ${{ if or(startswith(variables['Build.SourceBranch'], 'refs/heads/release/'), startswith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')) }}:
      - group: vh-prod
    - ${{ if not(or(startswith(variables['Build.SourceBranch'], 'refs/heads/release/'), startswith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'))) }}:
      - group: vh-preview

trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts_shaed
  pipelines:
  - pipeline: CI
    source: hmcts.vh-notification-api
    trigger: 
      branches:
      - master
      - hotfix/*
      - release/*

extends:
    template: templates/vh-release.yml@templates
    parameters:
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        environments:
          - ${{ parameters.environment }}
        deploymentBranch: ${{ parameters.deploymentBranch }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        deploymentBranch: resources.pipeline.CI.sourceBranch
      releaseParameters:
        runACTests: false
        runZapTests: ${{ parameters.RunZap }}
        subscription: $(env_Subscription)
        secrets_KeyVault: $(env_Secret_KeyVault)
        secrets_Subscription: $(env_Secret_Subscription)
        devOpsResource: vh_notification_api
        appName: vh-notification-api-$(environment)
        resourceGroup: vh-notification-api-$(environment)
        variables:
          - group: govuk-notify-test
            env:
             - Preview
             - Dev
             - AAT
             - Sandbox
             - Test1
             - Test2
             - Demo
          - group: govuk-notify-prod
            env:
             - PreProd
             - Prod
        appSettings:
          - name: ApplicationInsights:InstrumentationKey
            value: vh-core-infra-AppInsightsKey
            secret: true

          # AzureAd
          - name: AzureAd:ClientId
            value: vh-notification-api-appid
            secret: true
          - name: AzureAd:ClientSecret
            value: vh-notification-api-key
            secret: true
          - name: AzureAd:TenantId
            value: tenantid
            secret: true
          - name: AzureAd:VhVideoWebResourceId
            value: vh-notification-api-identifieruris
            secret: true
            
          # Services          
          - name: Services:VhNotificationApiResourceId
            value: vh-notification-api-identifieruris
            secret: true

          # GOV Notify Configuration
          - name: NotifyConfiguration:ApiKey
            value: $(notify-api-key)
            secret: true
            
          # Connection strings
          - name: ConnectionStrings:VhNotificationsApi
            value: vhnotificationDatabaseConnectionString
            secret: true
            
        acceptanceTestSettings:
          # AzureAd
          - name: ApplicationInsights:InstrumentationKey
            value: vh-core-infra-AppInsightsKey
            secret: true
          - name: AzureAd:TenantId
            value: tenantid
            secret: true
          - name: AzureAd:ClientId
            value: vh-notification-api-appid
            secret: true
          - name: AzureAd:ClientSecret
            value: vh-notification-api-key
            secret: true
          
          # Services          
          - name: Services:VhNotificationApiResourceId
            value: vh-notification-api-identifieruris
            secret: true
          - name: Services:NotificationApiUrl
            value: $(notification_api_url)

          # GOV Notify Configuration
          - name: NotifyConfiguration:ApiKey
            value: $(notify-api-key)
