# Set variables once
variables:
  - name: solutionType
    value : DotNetCore # angularDotNetCore, dotNetCore, angular
  - name: apiDirectory
    value : 'NotifyAPI/Notify.API'
  - name: sonarCloudExtraProperties
    value : |
      sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)\Coverage\coverage.opencover.xml
      sonar.coverage.exclusions=**/Program.cs, **/Startup.cs, **/Notify.API/Extensions/**, **/Notify.API/Swagger/**, **/Notify.API/ConfigureServicesExtensions.cs, **/Testing.Common/**, **/Testing.Common/Helper/, **/Testing.Common/Helper/Builders/Api, **/Testing.Common/Helper/Builders/Domain, **/NotifyApi.Common/**, **/NotifyApi.DAL/Mappings/**, **/NotifyApi.DAL/SeedData/**, **/NotifyApi.DAL/NotifyApiDbContext.cs, **/NotifyApi.DAL/**/DesignTimeHearingsContextFactory.cs, **/NotifyApi.DAL/Migrations/**, **/NotifyApi.Domain/Ddd/**, **/NotifyApi.Domain/Validations/**, **/NotifyApi.Services/**, **/NotifyApi.Events/Hub/EventHubClient.cs, **/Notify.API/KinlyApiTokenDelegatingHandler.cs
      sonar.cpd.exclusions="**/NotifyApi.DAL/Migrations/**"
  - name: coverletCoverageExclusions
    value : '[*]Notify.API.Extensions.*,[Notify.API]Notify.API.ConfigureServicesExtensions,[Notify.API]Notify.API.Startup,[Notify.API]Notify.API.Program,[*]Notify.API.Swagger.*,[NotifyApi.*Tests?]*,[*]NotifyApi.DAL.SeedData.*,[*]NotifyApi.DAL.Migrations.*,[*]NotifyApi.DAL.Mappings.*,[*]NotifyApi.Domain.Ddd.*,[*]NotifyApi.Domain.Validations.*,[NotifyApi.DAL]NotifyApi.DAL.NotifyApiDbContext,[NotifyApi.DAL]NotifyApi.DAL.DesignTimeHearingsContextFactory,[*]NotifyApi.Common.*,[*]Testing.Common.*'
  - name: integrationTestsAppSettingsTransform
    value : '
      "Services/NotifyApiUrl":"$(NotifyApiUrl)",
      "Services/VhNotifyApiResourceId":"$(vh-notify-api-identifieruris)"
      '
  - name: dalWorkingDirectory
    value : 'NotifyAPI/NotifyApi.DAL'
  - name: keyVaultName
    value : vhcoreinfrahtdev # Used to get secrets for integration tests
  - name: secretsFilter
    value : 'vh-notify-api-identifieruris,vh-user-api-identifieruris' # filters out secrets returned from key vault
  - name: infraKeyVaultName
    value : 'vhcoreinfradev'
  - name: infraSecretsFilter
    value : 'vh-core-infra-AppInsightsKey,VhNotifyDatabaseConnectionString'

# GitHub Repo that conatins build templates. Reference https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories
resources:
  repositories:
  - repository: azureDevOpsTemplates
    type: github
    name: hmcts/azure-devops-templates
    ref: refs/heads/master # ref name to use, defaults to 'refs/heads/master'
    endpoint: hmcts_shaed

trigger:
  branches:
    include:
    - master
    - release/*
    - hotfix/*
    
pr:
  - master

jobs:
  
- template: jobs/angularDotNetCore.yml@azureDevOpsTemplates # Template reference
  parameters:
    sonarCloudExtraProperties: $(sonarCloudExtraProperties)
    integrationTestsAppSettingsTransform: $(integrationTestsAppSettingsTransform)
    coverletCoverageExclusions: $(coverletCoverageExclusions)
    apiDirectory: $(apiDirectory)
    dalWorkingDirectory: $(dalWorkingDirectory)
    keyVaultName: $(keyVaultName)
    secretsFilter: $(secretsFilter),
    infraKeyVaultName: $(infraKeyVaultName)
    infraSecretsFilter: $(infraSecretsFilter)
    dotNetCoreVersion: '3.1.100'
