parameters:
- name: deploymentBranch
  displayName: Branch to Deploy
  type: string
  default: refs/heads/master

- name: environment
  displayName: Environment
  type: string
  default: Sandbox
  values:
  - Preview
  - Dev
  - AAT
  - Sandbox
  - Test1
  - Test2
  - Test3
  - Demo
  - Preprod
  - Prod

- name: RunZap
  displayName: Execute ZAP Tests
  type: boolean
  default: false

- name: RunACTests
  displayName: Execute AC Tests
  type: boolean
  default: true

- name: prodEnvs
  displayName: Environments Using Prod Subscription
  type: object
  default:
    - Prod
    - Preprod

# Set variables once
variables:
  - group: vh-domains-and-urls
  - group: vh-apps-settings-generic
  - group: vh-notification-api
  - ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
    - ${{ if containsValue(parameters.prodEnvs, parameters.environment) }}:
      - group: vh-prod
    - ${{ if not(containsValue(parameters.prodEnvs, parameters.environment)) }}:
      - group: vh-preview
  - ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
    - ${{ if or(startswith(variables['Build.SourceBranch'], 'refs/heads/release/'), startswith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')) }}:
      - group: vh-prod
    - ${{ if not(or(startswith(variables['Build.SourceBranch'], 'refs/heads/release/'), startswith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'))) }}:
      - group: vh-preview

trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts
  pipelines:
  - pipeline: CI
    source: hmcts.vh-notification-api
    trigger:
      enabled: true
      branches:
      - master
      - hotfix/*
      - release/*

extends:
    template: templates/vh-release.yml@templates
    parameters:
      ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
        environments:
          - ${{ parameters.environment }}
        deploymentBranch: ${{ parameters.deploymentBranch }}
      ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
        deploymentBranch: resources.pipeline.CI.sourceBranch
      releaseParameters:
        runACTests: ${{ parameters.RunACTests }}
        runZapTests: ${{ parameters.RunZap }}
        subscription: $(env_Subscription)
        secrets_KeyVault: $(env_Secret_KeyVault)
        secrets_Subscription: $(env_Secret_Subscription)
        devOpsResource: vh_notification_api
        appName: vh-notification-api-$(environment)
        resourceGroup: vh-notification-api-$(environment)
        variables:
          - group: govuk-notify-preview
            env:
             - Preview
          - group: govuk-notify-dev
            env:
             - Dev
          - group: govuk-notify-aat
            env:
             - AAT
          - group: govuk-notify-sandbox
            env:
             - Sandbox
          - group: govuk-notify-test1
            env:
             - Test1
             - Test2
          - group: govuk-notify-demo
            env:
             - Demo
          - group: govuk-notify-preprod
            env:
             - PreProd
          - group: govuk-notify-prod
            env:
             - Prod
        appSettings:
          - name: ApplicationInsights:InstrumentationKey
            value: vh-core-infra-AppInsightsKey
            secret: true
          - name: Services:VhNotificationApiResourceId
            value: vh-notification-api-identifieruris
            secret: true
          # AzureAd
          - name: AzureAd:ClientId
            value: vh-notification-api-appid
            secret: true
          - name: AzureAd:ClientSecret
            value: vh-notification-api-key
            secret: true
          - name: AzureAd:TenantId
            value: tenantid
            secret: true
          - name: AzureAd:VhNotificationApiResourceId
            value: vh-notification-api-identifieruris
            secret: true

          # GOV Notify Configuration
          - name: NotifyConfiguration:ApiKey
            value: $(notify-api-key)
          - name: NotifyConfiguration:CallbackSecret
            value: $(notify-callback-secret)
          - name: NotifyConfiguration:CreateIndividual
            value: $(CreateIndividual)
          - name: NotifyConfiguration:CreateRepresentative
            value: $(CreateRepresentative)
          - name: NotifyConfiguration:PasswordReset
            value: $(PasswordReset)
          - name: NotifyConfiguration:HearingConfirmationLip
            value: $(HearingConfirmationLip)
          - name: NotifyConfiguration:HearingConfirmationRepresentative
            value: $(HearingConfirmationRepresentative)
          - name: NotifyConfiguration:HearingConfirmationJudge
            value: $(HearingConfirmationJudge)
          - name: NotifyConfiguration:HearingConfirmationJoh
            value: $(HearingConfirmationJoh)
          - name: NotifyConfiguration:HearingConfirmationLipMultiDay
            value: $(HearingConfirmationLipMultiDay)
          - name: NotifyConfiguration:HearingConfirmationRepresentativeMultiDay
            value: $(HearingConfirmationRepresentativeMultiDay)
          - name: NotifyConfiguration:HearingConfirmationJudgeMultiDay
            value: $(HearingConfirmationJudgeMultiDay)
          - name: NotifyConfiguration:HearingConfirmationJohMultiDay
            value: $(HearingConfirmationJohMultiDay)
          - name: NotifyConfiguration:HearingAmendmentLip
            value: $(HearingAmendmentLip)
          - name: NotifyConfiguration:HearingAmendmentRepresentative
            value: $(HearingAmendmentRepresentative)
          - name: NotifyConfiguration:HearingAmendmentJudge
            value: $(HearingAmendmentJudge)
          - name: NotifyConfiguration:HearingAmendmentJoh
            value: $(HearingAmendmentJoh)
          - name: NotifyConfiguration:HearingReminderLip
            value: $(HearingReminderLip)
          - name: NotifyConfiguration:HearingReminderRepresentative
            value: $(HearingReminderRepresentative)
          - name: NotifyConfiguration:HearingReminderJoh
            value: $(HearingReminderJoh)
          - name: NotifyConfiguration:HearingConfirmationEJudJudge
            value: $(HearingConfirmationEJudJudge)
          - name: NotifyConfiguration:HearingConfirmationEJudJudgeMultiDay
            value: $(HearingConfirmationEJudJudgeMultiDay)
          - name: NotifyConfiguration:HearingAmendmentEJudJudge
            value: $(HearingAmendmentEJudJudge)
          - name: NotifyConfiguration:HearingAmendmentEJudJoh
            value: $(HearingAmendmentEJudJoh)
          - name: NotifyConfiguration:HearingReminderEJudJoh
            value: $(HearingReminderEJudJoh)
          - name: NotifyConfiguration:HearingConfirmationEJudJoh
            value: $(HearingConfirmationEJudJoh)
          - name: NotifyConfiguration:HearingConfirmationEJudJohMultiDay
            value: $(HearingConfirmationEJudJohMultiDay)
          - name: NotifyConfiguration:EJudJohDemoOrTest
            value: $(EJudJohDemoOrTest)
          - name: NotifyConfiguration:EJudJudgeDemoOrTest
            value: $(EJudJudgeDemoOrTest)
          - name: NotifyConfiguration:JudgeDemoOrTest
            value: $(JudgeDemoOrTest)
          - name: NotifyConfiguration:ParticipantDemoOrTest
            value: $(ParticipantDemoOrTest)
          - name: NotifyConfiguration:TelephoneHearingConfirmationLip
            value: $(TelephoneHearingConfirmation)
          - name: NotifyConfiguration:TelephoneHearingConfirmationLipMultiDay
            value: $(TelephoneHearingConfirmationMultiDay)
            
          # Connection strings
          - name: ConnectionStrings:VhNotificationsApi
            value: vhnotificationDatabaseConnectionString
            secret: true
            
        acceptanceTestSettings:
          # AzureAd
          - name: ApplicationInsights:InstrumentationKey
            value: vh-core-infra-AppInsightsKey
            secret: true
          - name: AzureAd:TenantId
            value: tenantid
            secret: true
          - name: AzureAd:ClientId
            value: vh-notification-api-appid
            secret: true
          - name: AzureAd:ClientSecret
            value: vh-notification-api-key
            secret: true
          
          # Services          
          - name: Services:VhNotificationApiResourceId
            value: vh-notification-api-identifieruris
            secret: true
          - name: Services:NotificationApiUrl
            value: $(notification_api_url_staging)

          # GOV Notify Configuration
          - name: NotifyConfiguration:ApiKey
            value: $(notify-api-key)
          - name: NotifyConfiguration:CallbackSecret
            value: $(notify-callback-secret)
          - name: NotifyConfiguration:CreateIndividual
            value: $(CreateIndividual)
          - name: NotifyConfiguration:CreateRepresentative
            value: $(CreateRepresentative)
          - name: NotifyConfiguration:PasswordReset
            value: $(PasswordReset)
          - name: NotifyConfiguration:HearingConfirmationLip
            value: $(HearingConfirmationLip)
          - name: NotifyConfiguration:HearingConfirmationRepresentative
            value: $(HearingConfirmationRepresentative)
          - name: NotifyConfiguration:HearingConfirmationJudge
            value: $(HearingConfirmationJudge)
          - name: NotifyConfiguration:HearingConfirmationJoh
            value: $(HearingConfirmationJoh)
          - name: NotifyConfiguration:HearingConfirmationLipMultiDay
            value: $(HearingConfirmationLipMultiDay)
          - name: NotifyConfiguration:HearingConfirmationRepresentativeMultiDay
            value: $(HearingConfirmationRepresentativeMultiDay)
          - name: NotifyConfiguration:HearingConfirmationJudgeMultiDay
            value: $(HearingConfirmationJudgeMultiDay)
          - name: NotifyConfiguration:HearingConfirmationJohMultiDay
            value: $(HearingConfirmationJohMultiDay)
          - name: NotifyConfiguration:HearingAmendmentLip
            value: $(HearingAmendmentLip)
          - name: NotifyConfiguration:HearingAmendmentRepresentative
            value: $(HearingAmendmentRepresentative)
          - name: NotifyConfiguration:HearingAmendmentJudge
            value: $(HearingAmendmentJudge)
          - name: NotifyConfiguration:HearingAmendmentJoh
            value: $(HearingAmendmentJoh)
          - name: NotifyConfiguration:HearingReminderLip
            value: $(HearingReminderLip)
          - name: NotifyConfiguration:HearingReminderRepresentative
            value: $(HearingReminderRepresentative)
          - name: NotifyConfiguration:HearingReminderJoh
            value: $(HearingReminderJoh)
          - name: NotifyConfiguration:HearingConfirmationEJudJudge
            value: $(HearingConfirmationEJudJudge)
          - name: NotifyConfiguration:HearingConfirmationEJudJudgeMultiDay
            value: $(HearingConfirmationEJudJudgeMultiDay)
          - name: NotifyConfiguration:HearingAmendmentEJudJudge
            value: $(HearingAmendmentEJudJudge)
          - name: NotifyConfiguration:HearingAmendmentEJudJoh
            value: $(HearingAmendmentEJudJoh)
          - name: NotifyConfiguration:HearingReminderEJudJoh
            value: $(HearingReminderEJudJoh)
          - name: NotifyConfiguration:HearingConfirmationEJudJoh
            value: $(HearingConfirmationEJudJoh)
          - name: NotifyConfiguration:HearingConfirmationEJudJohMultiDay
            value: $(HearingConfirmationEJudJohMultiDay)
          - name: NotifyConfiguration:EJudJohDemoOrTest
            value: $(EJudJohDemoOrTest)
          - name: NotifyConfiguration:EJudJudgeDemoOrTest
            value: $(EJudJudgeDemoOrTest)
          - name: NotifyConfiguration:JudgeDemoOrTest
            value: $(JudgeDemoOrTest)
          - name: NotifyConfiguration:ParticipantDemoOrTest
            value: $(ParticipantDemoOrTest)
          - name: NotifyConfiguration:TelephoneHearingConfirmationLip
            value: $(TelephoneHearingConfirmation)
          - name: NotifyConfiguration:TelephoneHearingConfirmationLipMultiDay
            value: $(TelephoneHearingConfirmationMultiDay)
