parameters:
- name: PackageApp
  displayName: Package App
  type: boolean
  default: true

- name: PackageACTests
  displayName: Package Acceptance Tests
  type: boolean
  default: false

- name: RunUnitTests
  displayName: Run Unit Tests
  type: boolean
  default: true

- name: RunIntegTests
  displayName: Run Integration Tests
  type: boolean
  default: true

- name: RunSonarCloudTests
  displayName: Run Sonar Cloud Analysis
  type: boolean
  default: false

- name: RunMutationTests
  displayName: Run Mutation Tests
  type: boolean
  default: false

- name: RunACTests
  displayName: Run Acceptance Tests
  type: boolean
  default: true

- name: testSettings
  type: object
  default:
    - name: ApplicationInsights:InstrumentationKey
      value: vh-core-infra-AppInsightsKey
    - name: AzureAd:ClientId
      value: vh-notification-api-appid
      secret: true
    - name: AzureAd:ClientSecret
      value: vh-notification-api-key
      secret: true
    - name: AzureAd:TenantId
      value: tenantid
      secret: true
    - name: Services:VhNotificationApiResourceId
      value: vh-notification-api-identifieruris
      secret: true
    - name: Services:NotificationApiUrl
      value: $(notification_api_url)
    
    # GOV Notify Configuration
    - name: NotifyConfiguration:ApiKey
      value: $(notify-api-key)

- name: appSettings
  type: object
  default:
  - name: ApplicationInsights:InstrumentationKey
    value: vh-core-infra-AppInsightsKey
  - name: AzureAd:ClientId
    value: vh-notification-api-appid
    secret: true
  - name: AzureAd:ClientSecret
    value: vh-notification-api-key
    secret: true
  - name: AzureAd:TenantId
    value: tenantid
    secret: true
  - name: VhServices:VhNotificationApiResourceId
    value: vh-notification-api-identifieruris
    secret: true
  
  # GOV Notify Configuration
  - name: NotifyConfiguration:ApiKey
    value: $(notify-api-key)
    secret: true

  # Connection strings
  - name: ConnectionStrings:VhNotificationsApi
    value: NotificationApiDb-connection-str
    secret: true

variables:
  - group: vh-domains-and-urls
  - group: vh-apps-settings-generic
  - group: vh-preview
  - group: govuk-notify-test

trigger:
  branches:
    include:
    - master
    - release/*
    - hotfix/*

pr:
  branches:
    include:
    - master

resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts_shaed
  containers:
  - container: dotnetsdk
    image: sspublicsbox.azurecr.io/vh/dotnet:3.1.102
    endpoint: sspublicsbox
  - container: dotnetsdk-cipipeline
    image: sspublicsbox.azurecr.io/vh/dotnet-cipipeline:3.1.102
    endpoint: sspublicsbox

extends:
  template: stages\dotnet-package.yml@templates
  parameters:
    coreProjectPath: NotificationAPI/Notification.API
    PackageApp: ${{ parameters.PackageApp }}
    PackageAcceptanceTests: ${{ parameters.PackageACTests }}
    Test: ${{ or(parameters.RunUnitTests, parameters.RunIntegTests, parameters.RunMutationTests) }}
    testParameters:
      baseAgent: windows-latest
      coreProjectPath: NotificationAPI/Notification.API
      unitTestProjectPath: NotificationAPI/NotificationApi.UnitTests
      integTestProjectPath: NotificationAPI/NotificationApi.IntegrationTests
      secrets_KeyVault: $(pr_Secret_KeyVault)
      secrets_Subscription: $(pr_Secret_Subscription)
      RunUnitTests: ${{ parameters.RunUnitTests }}
      RunIntegrationTests: ${{ parameters.RunIntegTests }}
      RunSonarCloud: ${{ parameters.RunSonarCloudTests }}
      RunStryker: ${{ parameters.RunMutationTests }}
      IntegrationTestSettings:
        - ${{ each setting in parameters.testSettings }}:
          - name: ${{ setting.name }}
            value: ${{ setting.value }}
            secret: ${{ setting.secret }}
            type: ${{ setting.type }}
      variables:
        - group: vh-notification-api
      coverletCoverageExclusions:
        - "[NotificationApi.*Tests?]*"
        - "[NotificationApi.API]Startup"
        - "[NotificationApi.Common]*"
        - "[Testing.Common]*"
      sonarCloud_ExtraProperties: |
        sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)/Coverage/coverage.opencover.xml
        sonar.coverage.exclusions="**/Notification.API/Swagger/**, **/Program.cs, **/Startup.cs, **/Testing.Common/**, **/NotificationAPI.Common/**, **/NotificationAPI.IntegrationTests/**, **/NotificationAPI.UnitTests/**, **/Notification.API/Extensions/**"
        sonar.cpd.exclusions="**/Program.cs, **/Startup.cs, **/Testing.Common/**, **/Notification.API/Swagger/**"
      StrykerBreak: 75
    ACTest: ${{ parameters.RunACTests }}
    releaseParameters:
      environment: Preview

      subscription: $(pr_Subscription)
      secrets_KeyVault: $(pr_Secret_KeyVault)
      secrets_Subscription: $(pr_Secret_Subscription)
      devOpsResource: vh_notification_api
      appName: vh-notification-api-$(environment)
      resourceGroup: vh-notification-api-$(environment)
      variables:
        - group: vh-notification-api
      appSettings: ${{ parameters.appSettings }}
      acceptanceTestSettings:
        - name: Services:NotificationApiUrl
          value: $(notification_api_url_staging)
        - ${{ each setting in parameters.testSettings }}:
          - name: ${{ setting.name }}
            value: ${{ setting.value }}
            secret: ${{ setting.secret }}
