using NotificationApi.Domain;
using NotificationApi.Domain.Enums;
using System;
using System.Collections.Generic;

namespace NotificationApi
{
    public class TemplateDataForEnvironments
    {
        private readonly IList<Template> _sourceTemplatesLocal = new List<Template>() {
            { new Template(new Guid("5C862F23-F12A-463E-A140-1C9C8D44EC0A"),NotificationType.CreateIndividual,MessageType.Email,"name,username,random password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E913CED8-CFA2-49EC-8DA4-9353F0105D97"),NotificationType.CreateRepresentative,MessageType.Email,"name,username,random password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("C4D0001F-1706-483C-AB64-0DCB53EB8216"),NotificationType.PasswordReset,MessageType.Email,"name,password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("811125FE-4CAB-4829-88ED-D3E7D4689CDD"),NotificationType.HearingConfirmationJudge,MessageType.Email,"case name,case number,judge,day month year,time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("1D4ACED7-4A0B-4610-B4C7-71F6C35B4143"),NotificationType.HearingConfirmationJoh,MessageType.Email,"case name,case number,judicial office holder,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("1F507F21-CEE6-430F-AB75-AA95980E369F"),NotificationType.HearingConfirmationLip,MessageType.Email,"case name,case number,name,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7CF9B49B-02D6-41C2-BCD0-71E2E9655731"),NotificationType.HearingConfirmationRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("70C29995-D6D6-48D4-AB1B-6F957A776F30"),NotificationType.HearingReminderJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("715017DB-24B5-4117-A47D-0F935054A5A0"),NotificationType.HearingReminderLip,MessageType.Email,"case name,case number,name,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("197D2B04-A600-41AE-BF68-8021D6EA0057"),NotificationType.HearingReminderRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("64AAA327-B087-4142-BE1A-94238D9248EA"),NotificationType.HearingAmendmentJudge,MessageType.Email,"case name,case number,judge,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("3210895A-C096-4029-B43E-9FDE4642A254"),NotificationType.HearingAmendmentJoh,MessageType.Email,"case name,case number,judicial office holder,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("A95A5C70-1E86-4DD6-8972-1993DFB21A18"),NotificationType.HearingAmendmentLip,MessageType.Email,"case name,case number,name,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("04A2DD3D-06BA-462B-A866-7FC802AAE69A"),NotificationType.HearingAmendmentRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F7E9BE27-5E7A-439D-B52E-4CFC56C9DD86"),NotificationType.HearingConfirmationJudgeMultiDay,MessageType.Email,"case name,case number,judge,Start Day Month Year,time,number of days,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("8E12EFD7-A6CB-4E43-8757-39CD1D292946"),NotificationType.HearingConfirmationJohMultiDay,MessageType.Email,"case name,case number,judicial office holder,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("04CD937D-C6EB-4932-A040-469123AFEF67"),NotificationType.HearingConfirmationLipMultiDay,MessageType.Email,"case name,case number,name,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("94A12C16-B291-4F5E-89F0-7AF625F5F51B"),NotificationType.HearingConfirmationRepresentativeMultiDay,MessageType.Email,"case name,case number,client name,solicitor name,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("ED3A7CC4-9F9B-4E3D-A522-5FEFCB59CA01"),NotificationType.HearingConfirmationEJudJudge,MessageType.Email,"case name,case number,judge,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2326B59A-4170-45DB-9638-789CA002FC20"),NotificationType.HearingConfirmationEJudJudgeMultiDay,MessageType.Email,"case name,case number,judge,Start Day Month Year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("339EDA5B-2E21-4D75-A768-75648E801738"),NotificationType.HearingAmendmentEJudJudge,MessageType.Email,"case name,case number,judge,New Day Month Year,Old Day Month Year,New time,Old time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("924E9BAE-0566-43DC-BE26-AAAB4B11F3C5"),NotificationType.HearingAmendmentEJudJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("45C68EC6-D869-45E4-BC83-E547620E05F9"),NotificationType.HearingReminderEJudJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("B71B697D-2AC4-4FFD-82C5-C270CD2AA22B"),NotificationType.HearingConfirmationEJudJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("A9CE6ED1-6618-411F-B100-E1335FED558B"),NotificationType.HearingConfirmationEJudJohMultiDay,MessageType.Email,"case name,case number,judicial office holder,Start Day Month Year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("B9D88AB8-6FE7-4FBA-98B6-3CA5E9EBBD31"),NotificationType.EJudJohDemoOrTest,MessageType.Email,"case number,test type,judicial office holder,username,date,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("B00E330B-14F7-4FF1-A511-824F309EC958"),NotificationType.ParticipantDemoOrTest,MessageType.Email,"test type,case number,date,name,username,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F966FE18-C817-46EB-8F19-BBE04CE0D940"),NotificationType.EJudJudgeDemoOrTest,MessageType.Email,"test type,date,time,case number,Judge",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E2D7E609-C42A-4C48-8EE3-C6F853267185"),NotificationType.JudgeDemoOrTest,MessageType.Email,"test type,date,time,case number,Judge,courtroom account username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("FC7485B2-36E8-4ED8-A529-3C7777B0212B"),NotificationType.TelephoneHearingConfirmation,MessageType.Email,"case name,case number,name,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("9EADD247-7B88-4D9F-892B-3F9C62AF67A5"),NotificationType.TelephoneHearingConfirmationMultiDay,MessageType.Email,"case name,case number,name,day month year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F521458D-EA14-445B-9FC3-1FA94EF55DC6"),NotificationType.CreateStaffMember,MessageType.Email,"Name,Username,Password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("4E8FBBB4-E501-4509-83E2-C0BBB42B9C3C"),NotificationType.HearingAmendmentStaffMember,MessageType.Email,"case name,case number,staff member,New Day Month Year,Old Day Month Year,New time,Old time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F8467D59-FFFB-44A5-85CE-AD5AE0180F37"),NotificationType.HearingConfirmationStaffMember,MessageType.Email,"case name,case number,staff member,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("C869C829-DF92-4BF9-A378-9EDF0C3518C2"),NotificationType.HearingConfirmationStaffMemberMultiDay,MessageType.Email,"case name,case number,staff member,Start Day Month Year,time,number of days,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("0A755E44-E29E-4BB6-81F2-648553E552BF"),NotificationType.StaffMemberDemoOrTest,MessageType.Email,"test type,date,time,case number,staff member",DateTime.UtcNow,DateTime.UtcNow ) },
        };

        private readonly IList<Template> _sourceTemplatesDev = new List<Template>() {
            { new Template(new Guid("94D06843-4608-4CDA-9933-9D0F3D7CE535"),NotificationType.CreateIndividual,MessageType.Email,"name,username,random password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E61575FC-05C8-40DA-B7A7-F7B1D04FF2DB"),NotificationType.CreateRepresentative,MessageType.Email,"name,username,random password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("15F91D90-56F0-480A-957D-11245F9C2CD9"),NotificationType.PasswordReset,MessageType.Email,"name,password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("6489A0F3-538F-49BC-86C5-B2787C71062A"),NotificationType.HearingConfirmationJudge,MessageType.Email,"case name,case number,judge,day month year,time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7DAF5DE2-256D-400F-854D-B8EA06DF2B84"),NotificationType.HearingConfirmationJoh,MessageType.Email,"case name,case number,judicial office holder,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2CF31323-3533-404D-9B52-73B33CE4A1BE"),NotificationType.HearingConfirmationLip,MessageType.Email,"case name,case number,name,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2D39FF6C-D036-4DE0-A953-F148F9839F3C"),NotificationType.HearingConfirmationRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("C0744BD9-4D9B-4F1A-BA3E-148C216FE1EA"),NotificationType.HearingReminderJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("385F78F3-0E77-45A5-A1B0-6CE793A9CDB2"),NotificationType.HearingReminderLip,MessageType.Email,"case name,case number,name,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7C90FEB4-F819-40B8-98CE-F83332B48014"),NotificationType.HearingReminderRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7C90E8DA-727B-4614-A3C6-B05219920CDE"),NotificationType.HearingAmendmentJudge,MessageType.Email,"case name,case number,judge,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("21A701AD-89D3-451A-9A87-544057541909"),NotificationType.HearingAmendmentJoh,MessageType.Email,"case name,case number,judicial office holder,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7F09A0C3-0AF6-49F1-85B4-259511FAD474"),NotificationType.HearingAmendmentLip,MessageType.Email,"case name,case number,name,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("79BBD6C3-14BA-4C8E-BD7C-10CEDFDFE3F0"),NotificationType.HearingAmendmentRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("A85B7C4B-BC32-41B9-AB3B-0EEDC0FF8617"),NotificationType.HearingConfirmationJudgeMultiDay,MessageType.Email,"case name,case number,judge,Start Day Month Year,time,number of days,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("77F66714-FAFC-4642-B505-33517E8A6BA8"),NotificationType.HearingConfirmationJohMultiDay,MessageType.Email,"case name,case number,judicial office holder,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("BF20004C-258B-4DE9-83A1-D7B260750B9F"),NotificationType.HearingConfirmationLipMultiDay,MessageType.Email,"case name,case number,name,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("C06B60B0-CA26-43EE-B6B6-7E5AA5A2B170"),NotificationType.HearingConfirmationRepresentativeMultiDay,MessageType.Email,"case name,case number,client name,solicitor name,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("28B905EA-ECA2-48D3-88EA-B87D578306E9"),NotificationType.HearingConfirmationEJudJudge,MessageType.Email,"case name,case number,judge,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("152F75BC-291C-4420-9411-F39FE8A433ED"),NotificationType.HearingConfirmationEJudJudgeMultiDay,MessageType.Email,"case name,case number,judge,Start Day Month Year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2FF7B633-E285-4E25-9029-83012DD448BA"),NotificationType.HearingAmendmentEJudJudge,MessageType.Email,"case name,case number,judge,New Day Month Year,Old Day Month Year,New time,Old time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("CA353650-C43B-46E4-890C-B8DAD47A825A"),NotificationType.HearingAmendmentEJudJoh,MessageType.Email,"case name,case number,judge,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("B5E2E627-398F-4FBF-8853-121D3007E043"),NotificationType.HearingReminderEJudJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("4B6C39A5-88AB-475C-9E3A-62BE1778A16D"),NotificationType.HearingConfirmationEJudJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("ED0F327E-324B-446C-BB0A-48BEA0F67786"),NotificationType.HearingConfirmationEJudJohMultiDay,MessageType.Email,"case name,case number,judicial office holder,Start Day Month Year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("6F16C9DF-9DDD-4C4D-A743-7D87853FD753"),NotificationType.EJudJohDemoOrTest,MessageType.Email,"case number,test type,judicial office holder,date,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F0898BA0-3C26-40C6-B311-1EC4B0E5B01C"),NotificationType.ParticipantDemoOrTest,MessageType.Email,"test type,case number,date,name,username,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("56E9FF91-267F-4154-814A-0281DD100CC6"),NotificationType.EJudJudgeDemoOrTest,MessageType.Email,"test type,date,time,case number,Judge",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E2709C28-9E12-4BC5-B2EA-3FC8147E7373"),NotificationType.JudgeDemoOrTest,MessageType.Email,"test type,date,time,case number,Judge,courtroom account username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("720E569B-4FBD-4529-8530-6A51C46EBD87"),NotificationType.TelephoneHearingConfirmation,MessageType.Email,"case name,case number,name,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E870E3BF-8C3D-477C-BFC1-EB4776ABBF66"),NotificationType.TelephoneHearingConfirmationMultiDay,MessageType.Email,"case name,case number,name,day month year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("15C78693-F4F1-48E2-A3A0-0C04DF40586C"),NotificationType.CreateStaffMember,MessageType.Email,"Name,Username,Password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F11C7848-8D7B-4045-9C6E-15E7C9EB9060"),NotificationType.HearingAmendmentStaffMember,MessageType.Email,"case name,case number,staff member,New Day Month Year,Old Day Month Year,New time,Old time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("CD2F20EB-5A32-42B9-A267-135D635FC9C7"),NotificationType.HearingConfirmationStaffMember,MessageType.Email,"case name,case number,staff member,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("5CCD4DD9-388B-402B-9D58-36720B4346BA"),NotificationType.HearingConfirmationStaffMemberMultiDay,MessageType.Email,"case name,case number,staff member,Start Day Month Year,time,number of days,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("3FCA3D41-4129-465D-BBD7-31DAC01D3CA5"),NotificationType.StaffMemberDemoOrTest,MessageType.Email,"test type,date,time,case number,staff member",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("BB116814-0D4E-4F4B-86B7-E04A437DB31F"),NotificationType.NewHearingReminderLIP,MessageType.Email,"case name, case number, name, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("17D911FE-3B90-4443-B113-CB4626179DE9"),NotificationType.NewHearingReminderRepresentative,MessageType.Email,"case name, case number, client name, solicitor name, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("31955C3E-4664-4D7B-A2D3-35CD01B7E923"),NotificationType.NewHearingReminderJOH,MessageType.Email,"case name, case number, judicial office holder, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },        
        };

        private readonly IList<Template> _sourceTemplatesPreview = new List<Template>() {
            { new Template(new Guid("94D06843-4608-4CDA-9933-9D0F3D7CE535"),NotificationType.CreateIndividual,MessageType.Email,"name,username,random password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E61575FC-05C8-40DA-B7A7-F7B1D04FF2DB"),NotificationType.CreateRepresentative,MessageType.Email,"name,username,random password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("15F91D90-56F0-480A-957D-11245F9C2CD9"),NotificationType.PasswordReset,MessageType.Email,"name,password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("6489A0F3-538F-49BC-86C5-B2787C71062A"),NotificationType.HearingConfirmationJudge,MessageType.Email,"case name,case number,judge,day month year,time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7DAF5DE2-256D-400F-854D-B8EA06DF2B84"),NotificationType.HearingConfirmationJoh,MessageType.Email,"case name,case number,judicial office holder,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2CF31323-3533-404D-9B52-73B33CE4A1BE"),NotificationType.HearingConfirmationLip,MessageType.Email,"case name,case number,name,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2D39FF6C-D036-4DE0-A953-F148F9839F3C"),NotificationType.HearingConfirmationRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("C0744BD9-4D9B-4F1A-BA3E-148C216FE1EA"),NotificationType.HearingReminderJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("385F78F3-0E77-45A5-A1B0-6CE793A9CDB2"),NotificationType.HearingReminderLip,MessageType.Email,"case name,case number,name,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7C90FEB4-F819-40B8-98CE-F83332B48014"),NotificationType.HearingReminderRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7C90E8DA-727B-4614-A3C6-B05219920CDE"),NotificationType.HearingAmendmentJudge,MessageType.Email,"case name,case number,judge,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("21A701AD-89D3-451A-9A87-544057541909"),NotificationType.HearingAmendmentJoh,MessageType.Email,"case name,case number,judicial office holder,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7F09A0C3-0AF6-49F1-85B4-259511FAD474"),NotificationType.HearingAmendmentLip,MessageType.Email,"case name,case number,name,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("79BBD6C3-14BA-4C8E-BD7C-10CEDFDFE3F0"),NotificationType.HearingAmendmentRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("A85B7C4B-BC32-41B9-AB3B-0EEDC0FF8617"),NotificationType.HearingConfirmationJudgeMultiDay,MessageType.Email,"case name,case number,judge,Start Day Month Year,time,number of days,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("77F66714-FAFC-4642-B505-33517E8A6BA8"),NotificationType.HearingConfirmationJohMultiDay,MessageType.Email,"case name,case number,judicial office holder,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("BF20004C-258B-4DE9-83A1-D7B260750B9F"),NotificationType.HearingConfirmationLipMultiDay,MessageType.Email,"case name,case number,name,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("C06B60B0-CA26-43EE-B6B6-7E5AA5A2B170"),NotificationType.HearingConfirmationRepresentativeMultiDay,MessageType.Email,"case name,case number,client name,solicitor name,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("28B905EA-ECA2-48D3-88EA-B87D578306E9"),NotificationType.HearingConfirmationEJudJudge,MessageType.Email,"case name,case number,judge,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("152F75BC-291C-4420-9411-F39FE8A433ED"),NotificationType.HearingConfirmationEJudJudgeMultiDay,MessageType.Email,"case name,case number,judge,Start Day Month Year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2FF7B633-E285-4E25-9029-83012DD448BA"),NotificationType.HearingAmendmentEJudJudge,MessageType.Email,"case name,case number,judge,New Day Month Year,Old Day Month Year,New time,Old time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("CA353650-C43B-46E4-890C-B8DAD47A825A"),NotificationType.HearingAmendmentEJudJoh,MessageType.Email,"case name,case number,judge,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("B5E2E627-398F-4FBF-8853-121D3007E043"),NotificationType.HearingReminderEJudJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("4B6C39A5-88AB-475C-9E3A-62BE1778A16D"),NotificationType.HearingConfirmationEJudJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("ED0F327E-324B-446C-BB0A-48BEA0F67786"),NotificationType.HearingConfirmationEJudJohMultiDay,MessageType.Email,"case name,case number,judicial office holder,Start Day Month Year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("6F16C9DF-9DDD-4C4D-A743-7D87853FD753"),NotificationType.EJudJohDemoOrTest,MessageType.Email,"case number,test type,judicial office holder,date,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F0898BA0-3C26-40C6-B311-1EC4B0E5B01C"),NotificationType.ParticipantDemoOrTest,MessageType.Email,"test type,case number,date,name,username,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("56E9FF91-267F-4154-814A-0281DD100CC6"),NotificationType.EJudJudgeDemoOrTest,MessageType.Email,"test type,date,time,case number,Judge",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E2709C28-9E12-4BC5-B2EA-3FC8147E7373"),NotificationType.JudgeDemoOrTest,MessageType.Email,"test type,date,time,case number,Judge,courtroom account username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("720E569B-4FBD-4529-8530-6A51C46EBD87"),NotificationType.TelephoneHearingConfirmation,MessageType.Email,"case name,case number,name,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E870E3BF-8C3D-477C-BFC1-EB4776ABBF66"),NotificationType.TelephoneHearingConfirmationMultiDay,MessageType.Email,"case name,case number,name,day month year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("15C78693-F4F1-48E2-A3A0-0C04DF40586C"),NotificationType.CreateStaffMember,MessageType.Email,"Name,Username,Password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F11C7848-8D7B-4045-9C6E-15E7C9EB9060"),NotificationType.HearingAmendmentStaffMember,MessageType.Email,"case name,case number,staff member,New Day Month Year,Old Day Month Year,New time,Old time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("CD2F20EB-5A32-42B9-A267-135D635FC9C7"),NotificationType.HearingConfirmationStaffMember,MessageType.Email,"case name,case number,staff member,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("5CCD4DD9-388B-402B-9D58-36720B4346BA"),NotificationType.HearingConfirmationStaffMemberMultiDay,MessageType.Email,"case name,case number,staff member,Start Day Month Year,time,number of days,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("3FCA3D41-4129-465D-BBD7-31DAC01D3CA5"),NotificationType.StaffMemberDemoOrTest,MessageType.Email,"test type,date,time,case number,staff member",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("BB116814-0D4E-4F4B-86B7-E04A437DB31F"),NotificationType.NewHearingReminderLIP,MessageType.Email,"case name, case number, name, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("17D911FE-3B90-4443-B113-CB4626179DE9"),NotificationType.NewHearingReminderRepresentative,MessageType.Email,"case name, case number, client name, solicitor name, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("31955C3E-4664-4D7B-A2D3-35CD01B7E923"),NotificationType.NewHearingReminderJOH,MessageType.Email,"case name, case number, judicial office holder, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },        
        };

        private readonly IList<Template> _sourceTemplatesAAT = new List<Template>()
        {
            { new Template(new Guid("94D06843-4608-4CDA-9933-9D0F3D7CE535"),NotificationType.CreateIndividual,MessageType.Email,"name,username,random password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E61575FC-05C8-40DA-B7A7-F7B1D04FF2DB"),NotificationType.CreateRepresentative,MessageType.Email,"name,username,random password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("15F91D90-56F0-480A-957D-11245F9C2CD9"),NotificationType.PasswordReset,MessageType.Email,"name,password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("6489A0F3-538F-49BC-86C5-B2787C71062A"),NotificationType.HearingConfirmationJudge,MessageType.Email,"case name,case number,judge,day month year,time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7DAF5DE2-256D-400F-854D-B8EA06DF2B84"),NotificationType.HearingConfirmationJoh,MessageType.Email,"case name,case number,judicial office holder,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2CF31323-3533-404D-9B52-73B33CE4A1BE"),NotificationType.HearingConfirmationLip,MessageType.Email,"case name,case number,name,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2D39FF6C-D036-4DE0-A953-F148F9839F3C"),NotificationType.HearingConfirmationRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("C0744BD9-4D9B-4F1A-BA3E-148C216FE1EA"),NotificationType.HearingReminderJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("385F78F3-0E77-45A5-A1B0-6CE793A9CDB2"),NotificationType.HearingReminderLip,MessageType.Email,"case name,case number,name,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7C90FEB4-F819-40B8-98CE-F83332B48014"),NotificationType.HearingReminderRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7C90E8DA-727B-4614-A3C6-B05219920CDE"),NotificationType.HearingAmendmentJudge,MessageType.Email,"case name,case number,judge,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("21A701AD-89D3-451A-9A87-544057541909"),NotificationType.HearingAmendmentJoh,MessageType.Email,"case name,case number,judicial office holder,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7F09A0C3-0AF6-49F1-85B4-259511FAD474"),NotificationType.HearingAmendmentLip,MessageType.Email,"case name,case number,name,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("79BBD6C3-14BA-4C8E-BD7C-10CEDFDFE3F0"),NotificationType.HearingAmendmentRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("A85B7C4B-BC32-41B9-AB3B-0EEDC0FF8617"),NotificationType.HearingConfirmationJudgeMultiDay,MessageType.Email,"case name,case number,judge,Start Day Month Year,time,number of days,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("77F66714-FAFC-4642-B505-33517E8A6BA8"),NotificationType.HearingConfirmationJohMultiDay,MessageType.Email,"case name,case number,judicial office holder,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("BF20004C-258B-4DE9-83A1-D7B260750B9F"),NotificationType.HearingConfirmationLipMultiDay,MessageType.Email,"case name,case number,name,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("C06B60B0-CA26-43EE-B6B6-7E5AA5A2B170"),NotificationType.HearingConfirmationRepresentativeMultiDay,MessageType.Email,"case name,case number,client name,solicitor name,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("28B905EA-ECA2-48D3-88EA-B87D578306E9"),NotificationType.HearingConfirmationEJudJudge,MessageType.Email,"case name,case number,judge,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("152F75BC-291C-4420-9411-F39FE8A433ED"),NotificationType.HearingConfirmationEJudJudgeMultiDay,MessageType.Email,"case name,case number,judge,Start Day Month Year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2FF7B633-E285-4E25-9029-83012DD448BA"),NotificationType.HearingAmendmentEJudJudge,MessageType.Email,"case name,case number,judge,New Day Month Year,Old Day Month Year,New time,Old time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("CA353650-C43B-46E4-890C-B8DAD47A825A"),NotificationType.HearingAmendmentEJudJoh,MessageType.Email,"case name,case number,judge,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("B5E2E627-398F-4FBF-8853-121D3007E043"),NotificationType.HearingReminderEJudJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("4B6C39A5-88AB-475C-9E3A-62BE1778A16D"),NotificationType.HearingConfirmationEJudJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("ED0F327E-324B-446C-BB0A-48BEA0F67786"),NotificationType.HearingConfirmationEJudJohMultiDay,MessageType.Email,"case name,case number,judicial office holder,Start Day Month Year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("6F16C9DF-9DDD-4C4D-A743-7D87853FD753"),NotificationType.EJudJohDemoOrTest,MessageType.Email,"case number,test type,judicial office holder,date,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F0898BA0-3C26-40C6-B311-1EC4B0E5B01C"),NotificationType.ParticipantDemoOrTest,MessageType.Email,"test type,case number,date,name,username,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("56E9FF91-267F-4154-814A-0281DD100CC6"),NotificationType.EJudJudgeDemoOrTest,MessageType.Email,"test type,date,time,case number,Judge",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E2709C28-9E12-4BC5-B2EA-3FC8147E7373"),NotificationType.JudgeDemoOrTest,MessageType.Email,"test type,date,time,case number,Judge,courtroom account username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("720E569B-4FBD-4529-8530-6A51C46EBD87"),NotificationType.TelephoneHearingConfirmation,MessageType.Email,"case name,case number,name,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E870E3BF-8C3D-477C-BFC1-EB4776ABBF66"),NotificationType.TelephoneHearingConfirmationMultiDay,MessageType.Email,"case name,case number,name,day month year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("15C78693-F4F1-48E2-A3A0-0C04DF40586C"),NotificationType.CreateStaffMember,MessageType.Email,"Name,Username,Password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F11C7848-8D7B-4045-9C6E-15E7C9EB9060"),NotificationType.HearingAmendmentStaffMember,MessageType.Email,"case name,case number,staff member,New Day Month Year,Old Day Month Year,New time,Old time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("CD2F20EB-5A32-42B9-A267-135D635FC9C7"),NotificationType.HearingConfirmationStaffMember,MessageType.Email,"case name,case number,staff member,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("5CCD4DD9-388B-402B-9D58-36720B4346BA"),NotificationType.HearingConfirmationStaffMemberMultiDay,MessageType.Email,"case name,case number,staff member,Start Day Month Year,time,number of days,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("3FCA3D41-4129-465D-BBD7-31DAC01D3CA5"),NotificationType.StaffMemberDemoOrTest,MessageType.Email,"test type,date,time,case number,staff member",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("BB116814-0D4E-4F4B-86B7-E04A437DB31F"),NotificationType.NewHearingReminderLIP,MessageType.Email,"case name, case number, name, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("17D911FE-3B90-4443-B113-CB4626179DE9"),NotificationType.NewHearingReminderRepresentative,MessageType.Email,"case name, case number, client name, solicitor name, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("31955C3E-4664-4D7B-A2D3-35CD01B7E923"),NotificationType.NewHearingReminderJOH,MessageType.Email,"case name, case number, judicial office holder, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },
        };

        private readonly IList<Template> _sourceTemplatesTest1 = new List<Template>()
        {
            { new Template(new Guid("94D06843-4608-4CDA-9933-9D0F3D7CE535"),NotificationType.CreateIndividual,MessageType.Email,"name,username,random password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E61575FC-05C8-40DA-B7A7-F7B1D04FF2DB"),NotificationType.CreateRepresentative,MessageType.Email,"name,username,random password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("15F91D90-56F0-480A-957D-11245F9C2CD9"),NotificationType.PasswordReset,MessageType.Email,"name,password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("6489A0F3-538F-49BC-86C5-B2787C71062A"),NotificationType.HearingConfirmationJudge,MessageType.Email,"case name,case number,judge,day month year,time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7DAF5DE2-256D-400F-854D-B8EA06DF2B84"),NotificationType.HearingConfirmationJoh,MessageType.Email,"case name,case number,judicial office holder,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2CF31323-3533-404D-9B52-73B33CE4A1BE"),NotificationType.HearingConfirmationLip,MessageType.Email,"case name,case number,name,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2D39FF6C-D036-4DE0-A953-F148F9839F3C"),NotificationType.HearingConfirmationRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("C0744BD9-4D9B-4F1A-BA3E-148C216FE1EA"),NotificationType.HearingReminderJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("385F78F3-0E77-45A5-A1B0-6CE793A9CDB2"),NotificationType.HearingReminderLip,MessageType.Email,"case name,case number,name,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7C90FEB4-F819-40B8-98CE-F83332B48014"),NotificationType.HearingReminderRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7C90E8DA-727B-4614-A3C6-B05219920CDE"),NotificationType.HearingAmendmentJudge,MessageType.Email,"case name,case number,judge,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("21A701AD-89D3-451A-9A87-544057541909"),NotificationType.HearingAmendmentJoh,MessageType.Email,"case name,case number,judicial office holder,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7F09A0C3-0AF6-49F1-85B4-259511FAD474"),NotificationType.HearingAmendmentLip,MessageType.Email,"case name,case number,name,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("79BBD6C3-14BA-4C8E-BD7C-10CEDFDFE3F0"),NotificationType.HearingAmendmentRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("A85B7C4B-BC32-41B9-AB3B-0EEDC0FF8617"),NotificationType.HearingConfirmationJudgeMultiDay,MessageType.Email,"case name,case number,judge,Start Day Month Year,time,number of days,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("77F66714-FAFC-4642-B505-33517E8A6BA8"),NotificationType.HearingConfirmationJohMultiDay,MessageType.Email,"case name,case number,judicial office holder,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("BF20004C-258B-4DE9-83A1-D7B260750B9F"),NotificationType.HearingConfirmationLipMultiDay,MessageType.Email,"case name,case number,name,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("C06B60B0-CA26-43EE-B6B6-7E5AA5A2B170"),NotificationType.HearingConfirmationRepresentativeMultiDay,MessageType.Email,"case name,case number,client name,solicitor name,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("28B905EA-ECA2-48D3-88EA-B87D578306E9"),NotificationType.HearingConfirmationEJudJudge,MessageType.Email,"case name,case number,judge,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("152F75BC-291C-4420-9411-F39FE8A433ED"),NotificationType.HearingConfirmationEJudJudgeMultiDay,MessageType.Email,"case name,case number,judge,Start Day Month Year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2FF7B633-E285-4E25-9029-83012DD448BA"),NotificationType.HearingAmendmentEJudJudge,MessageType.Email,"case name,case number,judge,New Day Month Year,Old Day Month Year,New time,Old time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("CA353650-C43B-46E4-890C-B8DAD47A825A"),NotificationType.HearingAmendmentEJudJoh,MessageType.Email,"case name,case number,judge,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("B5E2E627-398F-4FBF-8853-121D3007E043"),NotificationType.HearingReminderEJudJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("4B6C39A5-88AB-475C-9E3A-62BE1778A16D"),NotificationType.HearingConfirmationEJudJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("ED0F327E-324B-446C-BB0A-48BEA0F67786"),NotificationType.HearingConfirmationEJudJohMultiDay,MessageType.Email,"case name,case number,judicial office holder,Start Day Month Year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("6F16C9DF-9DDD-4C4D-A743-7D87853FD753"),NotificationType.EJudJohDemoOrTest,MessageType.Email,"case number,test type,judicial office holder,date,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F0898BA0-3C26-40C6-B311-1EC4B0E5B01C"),NotificationType.ParticipantDemoOrTest,MessageType.Email,"test type,case number,date,name,username,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("56E9FF91-267F-4154-814A-0281DD100CC6"),NotificationType.EJudJudgeDemoOrTest,MessageType.Email,"test type,date,time,case number,Judge",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E2709C28-9E12-4BC5-B2EA-3FC8147E7373"),NotificationType.JudgeDemoOrTest,MessageType.Email,"test type,date,time,case number,Judge,courtroom account username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("720E569B-4FBD-4529-8530-6A51C46EBD87"),NotificationType.TelephoneHearingConfirmation,MessageType.Email,"case name,case number,name,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E870E3BF-8C3D-477C-BFC1-EB4776ABBF66"),NotificationType.TelephoneHearingConfirmationMultiDay,MessageType.Email,"case name,case number,name,day month year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("15C78693-F4F1-48E2-A3A0-0C04DF40586C"),NotificationType.CreateStaffMember,MessageType.Email,"Name,Username,Password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F11C7848-8D7B-4045-9C6E-15E7C9EB9060"),NotificationType.HearingAmendmentStaffMember,MessageType.Email,"case name,case number,staff member,New Day Month Year,Old Day Month Year,New time,Old time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("CD2F20EB-5A32-42B9-A267-135D635FC9C7"),NotificationType.HearingConfirmationStaffMember,MessageType.Email,"case name,case number,staff member,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("5CCD4DD9-388B-402B-9D58-36720B4346BA"),NotificationType.HearingConfirmationStaffMemberMultiDay,MessageType.Email,"case name,case number,staff member,Start Day Month Year,time,number of days,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("3FCA3D41-4129-465D-BBD7-31DAC01D3CA5"),NotificationType.StaffMemberDemoOrTest,MessageType.Email,"test type,date,time,case number,staff member",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("BB116814-0D4E-4F4B-86B7-E04A437DB31F"),NotificationType.NewHearingReminderLIP,MessageType.Email,"case name, case number, name, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("17D911FE-3B90-4443-B113-CB4626179DE9"),NotificationType.NewHearingReminderRepresentative,MessageType.Email,"case name, case number, client name, solicitor name, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("31955C3E-4664-4D7B-A2D3-35CD01B7E923"),NotificationType.NewHearingReminderJOH,MessageType.Email,"case name, case number, judicial office holder, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },
        };
        
        private readonly IList<Template> _sourceTemplatesDemo = new List<Template>()
        {
            { new Template(new Guid("94D06843-4608-4CDA-9933-9D0F3D7CE535"),NotificationType.CreateIndividual,MessageType.Email,"name,username,random password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E61575FC-05C8-40DA-B7A7-F7B1D04FF2DB"),NotificationType.CreateRepresentative,MessageType.Email,"name,username,random password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("15F91D90-56F0-480A-957D-11245F9C2CD9"),NotificationType.PasswordReset,MessageType.Email,"name,password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("6489A0F3-538F-49BC-86C5-B2787C71062A"),NotificationType.HearingConfirmationJudge,MessageType.Email,"case name,case number,judge,day month year,time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7DAF5DE2-256D-400F-854D-B8EA06DF2B84"),NotificationType.HearingConfirmationJoh,MessageType.Email,"case name,case number,judicial office holder,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2CF31323-3533-404D-9B52-73B33CE4A1BE"),NotificationType.HearingConfirmationLip,MessageType.Email,"case name,case number,name,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2D39FF6C-D036-4DE0-A953-F148F9839F3C"),NotificationType.HearingConfirmationRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,Day Month Year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("C0744BD9-4D9B-4F1A-BA3E-148C216FE1EA"),NotificationType.HearingReminderJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("385F78F3-0E77-45A5-A1B0-6CE793A9CDB2"),NotificationType.HearingReminderLip,MessageType.Email,"case name,case number,name,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7C90FEB4-F819-40B8-98CE-F83332B48014"),NotificationType.HearingReminderRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7C90E8DA-727B-4614-A3C6-B05219920CDE"),NotificationType.HearingAmendmentJudge,MessageType.Email,"case name,case number,judge,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("21A701AD-89D3-451A-9A87-544057541909"),NotificationType.HearingAmendmentJoh,MessageType.Email,"case name,case number,judicial office holder,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("7F09A0C3-0AF6-49F1-85B4-259511FAD474"),NotificationType.HearingAmendmentLip,MessageType.Email,"case name,case number,name,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("79BBD6C3-14BA-4C8E-BD7C-10CEDFDFE3F0"),NotificationType.HearingAmendmentRepresentative,MessageType.Email,"case name,case number,client name,solicitor name,New Day Month Year,Old Day Month Year,New time,Old time,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("A85B7C4B-BC32-41B9-AB3B-0EEDC0FF8617"),NotificationType.HearingConfirmationJudgeMultiDay,MessageType.Email,"case name,case number,judge,Start Day Month Year,time,number of days,courtroom account username,account password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("77F66714-FAFC-4642-B505-33517E8A6BA8"),NotificationType.HearingConfirmationJohMultiDay,MessageType.Email,"case name,case number,judicial office holder,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("BF20004C-258B-4DE9-83A1-D7B260750B9F"),NotificationType.HearingConfirmationLipMultiDay,MessageType.Email,"case name,case number,name,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("C06B60B0-CA26-43EE-B6B6-7E5AA5A2B170"),NotificationType.HearingConfirmationRepresentativeMultiDay,MessageType.Email,"case name,case number,client name,solicitor name,Start Day Month Year,time,number of days,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("28B905EA-ECA2-48D3-88EA-B87D578306E9"),NotificationType.HearingConfirmationEJudJudge,MessageType.Email,"case name,case number,judge,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("152F75BC-291C-4420-9411-F39FE8A433ED"),NotificationType.HearingConfirmationEJudJudgeMultiDay,MessageType.Email,"case name,case number,judge,Start Day Month Year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("2FF7B633-E285-4E25-9029-83012DD448BA"),NotificationType.HearingAmendmentEJudJudge,MessageType.Email,"case name,case number,judge,New Day Month Year,Old Day Month Year,New time,Old time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("CA353650-C43B-46E4-890C-B8DAD47A825A"),NotificationType.HearingAmendmentEJudJoh,MessageType.Email,"case name,case number,judge,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("B5E2E627-398F-4FBF-8853-121D3007E043"),NotificationType.HearingReminderEJudJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("4B6C39A5-88AB-475C-9E3A-62BE1778A16D"),NotificationType.HearingConfirmationEJudJoh,MessageType.Email,"case name,case number,judicial office holder,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("ED0F327E-324B-446C-BB0A-48BEA0F67786"),NotificationType.HearingConfirmationEJudJohMultiDay,MessageType.Email,"case name,case number,judicial office holder,Start Day Month Year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("6F16C9DF-9DDD-4C4D-A743-7D87853FD753"),NotificationType.EJudJohDemoOrTest,MessageType.Email,"case number,test type,judicial office holder,date,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F0898BA0-3C26-40C6-B311-1EC4B0E5B01C"),NotificationType.ParticipantDemoOrTest,MessageType.Email,"test type,case number,date,name,username,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("56E9FF91-267F-4154-814A-0281DD100CC6"),NotificationType.EJudJudgeDemoOrTest,MessageType.Email,"test type,date,time,case number,Judge",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E2709C28-9E12-4BC5-B2EA-3FC8147E7373"),NotificationType.JudgeDemoOrTest,MessageType.Email,"test type,date,time,case number,Judge,courtroom account username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("720E569B-4FBD-4529-8530-6A51C46EBD87"),NotificationType.TelephoneHearingConfirmation,MessageType.Email,"case name,case number,name,day month year,time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("E870E3BF-8C3D-477C-BFC1-EB4776ABBF66"),NotificationType.TelephoneHearingConfirmationMultiDay,MessageType.Email,"case name,case number,name,day month year,time,number of days",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("15C78693-F4F1-48E2-A3A0-0C04DF40586C"),NotificationType.CreateStaffMember,MessageType.Email,"Name,Username,Password",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("F11C7848-8D7B-4045-9C6E-15E7C9EB9060"),NotificationType.HearingAmendmentStaffMember,MessageType.Email,"case name,case number,staff member,New Day Month Year,Old Day Month Year,New time,Old time",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("CD2F20EB-5A32-42B9-A267-135D635FC9C7"),NotificationType.HearingConfirmationStaffMember,MessageType.Email,"case name,case number,staff member,day month year,time,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("5CCD4DD9-388B-402B-9D58-36720B4346BA"),NotificationType.HearingConfirmationStaffMemberMultiDay,MessageType.Email,"case name,case number,staff member,Start Day Month Year,time,number of days,username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("3FCA3D41-4129-465D-BBD7-31DAC01D3CA5"),NotificationType.StaffMemberDemoOrTest,MessageType.Email,"test type,date,time,case number,staff member",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("BB116814-0D4E-4F4B-86B7-E04A437DB31F"),NotificationType.NewHearingReminderLIP,MessageType.Email,"case name, case number, name, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("17D911FE-3B90-4443-B113-CB4626179DE9"),NotificationType.NewHearingReminderRepresentative,MessageType.Email,"case name, case number, client name, solicitor name, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },
            { new Template(new Guid("31955C3E-4664-4D7B-A2D3-35CD01B7E923"),NotificationType.NewHearingReminderJOH,MessageType.Email,"case name, case number, judicial office holder, day month year, time, username",DateTime.UtcNow,DateTime.UtcNow ) },
        };
        
        private readonly IList<Template> _sourceTemplatesPreProd = new List<Template>()
        {
        };
        private readonly IList<Template> _sourceTemplatesProd = new List<Template>()
        {
        };

        public IList<Template> Get(string environment)
        {
            switch (environment)
            {
                case "Local":
                    return _sourceTemplatesLocal;
                case "Dev":
                    return _sourceTemplatesDev;
                case "Preview":
                    return _sourceTemplatesPreview;
                case "AAT":
                    return _sourceTemplatesAAT;
                case "Test1":
                    return _sourceTemplatesTest1;
                case "Demo":
                    return _sourceTemplatesDemo;
                case "PreProd":
                    return _sourceTemplatesPreProd;
                case "Prod":
                    return _sourceTemplatesProd;

                default:
                    throw new Exception("Environment variable is not set - unable to find the list of templates");
            }
        }
    }
}
