version: '3.4'

services:
  notifyapi:
    container_name: notifyapi
    image: ${DOCKER_REGISTRY-}notifyapi
    restart: always
    build:
      context: .
      dockerfile: Notify.API/Dockerfile
    depends_on:
      - "db"
    environment:
      SQLCONNSTR_VhNotifyAPi: 'Server=db;Database=VhNotifyApi;User ID=sa;Password=VeryStrongPassword!'

  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    expose:
      - "1433"
    environment:
      ACCEPT_EULA: 'yes'
      SA_PASSWORD: 'VeryStrongPassword!'
